// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type SuccessEnvelope = {
    success: boolean;
    /**
     * Response payload (varies by endpoint).
     */
    data?: unknown;
};

export type ErrorEnvelope = {
    success: boolean;
    error: string;
};

export type Wallet = {
    address?: string;
    network?: string;
};

export type NativeBalance = {
    /**
     * Raw wei balance as a decimal string.
     */
    balance?: string;
};

export type Token = {
    token_address?: string;
    symbol?: string;
    name?: string;
    decimals?: string;
    balance?: string;
    balance_formatted?: string;
    usd_price?: string;
    usd_value?: string;
    logo?: string;
    possible_spam?: boolean;
};

export type Nft = {
    token_address?: string;
    token_id?: string;
    name?: string;
    symbol?: string;
    token_uri?: string;
    metadata?: string;
    amount?: string;
    contract_type?: string;
};

export type Transaction = {
    hash?: string;
    from_address?: string;
    to_address?: string;
    value?: string;
    block_number?: string;
    block_timestamp?: string;
    gas?: string;
    gas_price?: string;
    transaction_fee?: string;
};

export type HistoryEntry = {
    hash?: string;
    category?: string;
    summary?: string;
    block_timestamp?: string;
    block_number?: string;
    transaction_fee?: string;
    from_address?: string;
    to_address?: string;
};

export type DeFiPosition = {
    protocol_id?: string;
    protocol_name?: string;
    protocol_logo?: string;
    chain?: string;
    position?: {
        [key: string]: unknown;
    };
};

export type NetWorth = {
    total_networth_usd?: string;
    chains?: Array<ChainWorth>;
};

export type ChainWorth = {
    chain?: string;
    networth_usd?: string;
};

export type PnLSummary = {
    total_realized_profit_usd?: string;
    total_unrealised_profit_usd?: string;
    total_count_of_trades?: number;
    total_count_of_winning_trades?: number;
    total_count_of_losing_trades?: number;
};

export type TokenPnL = {
    token_address?: string;
    token_symbol?: string;
    token_name?: string;
    realized_profit_usd?: string;
    unrealised_profit_usd?: string;
    count_of_trades?: number;
    avg_buy_price_usd?: string;
    avg_sell_price_usd?: string;
};

export type EnsInfo = {
    name?: string;
    address?: string;
};

export type Approval = {
    token_address?: string;
    token_symbol?: string;
    token_name?: string;
    spender?: string;
    spender_label?: string;
    value?: string;
    value_formatted?: string;
    block_timestamp?: string;
};

export type LifiChain = {
    key?: string;
    name?: string;
    id?: number;
    coin?: string;
    chainType?: string;
    mainnet?: boolean;
    logoURI?: string;
    nativeToken?: LifiToken;
    metamask?: {
        chainId?: string;
        chainName?: string;
        rpcUrls?: Array<string>;
        blockExplorerUrls?: Array<string>;
    };
};

export type LifiToken = {
    address?: string;
    symbol?: string;
    name?: string;
    decimals?: number;
    chainId?: number;
    logoURI?: string;
    priceUSD?: string;
};

export type LifiGasCost = {
    amount?: string;
    amountUSD?: string;
    token?: LifiToken;
};

export type LifiQuote = {
    transactionRequest?: {
        from?: string;
        to?: string;
        data?: string;
        value?: string;
        gasPrice?: string;
        gasLimit?: string;
        chainId?: number;
    };
    estimate?: {
        fromAmount?: string;
        toAmount?: string;
        toAmountMin?: string;
        gasCosts?: Array<LifiGasCost>;
        executionDuration?: number;
        fromAmountUSD?: string;
        toAmountUSD?: string;
    };
    action?: {
        fromToken?: LifiToken;
        toToken?: LifiToken;
        fromAmount?: string;
        slippage?: number;
        fromChainId?: number;
        toChainId?: number;
    };
};

export type Address = string;

/**
 * Moralis chain identifier. Defaults to `eth`.
 */
export type Chain = 'eth' | 'polygon' | 'bsc' | 'optimism' | 'arbitrum' | 'base' | 'avalanche';

/**
 * Lookback window in days. 0 means all time.
 */
export type Days = number;

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Server is healthy
     */
    200: SuccessEnvelope;
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];

export type GetWalletData = {
    body?: never;
    path: {
        address: string;
    };
    query?: never;
    url: '/api/v1/wallets/{address}';
};

export type GetWalletErrors = {
    /**
     * Wallet not found
     */
    404: ErrorEnvelope;
};

export type GetWalletError = GetWalletErrors[keyof GetWalletErrors];

export type GetWalletResponses = {
    /**
     * Wallet found
     */
    200: SuccessEnvelope & {
        data?: Wallet;
    };
};

export type GetWalletResponse = GetWalletResponses[keyof GetWalletResponses];

export type GetNativeBalanceData = {
    body?: never;
    path: {
        address: string;
    };
    query?: {
        /**
         * Moralis chain identifier. Defaults to `eth`.
         */
        chain?: 'eth' | 'polygon' | 'bsc' | 'optimism' | 'arbitrum' | 'base' | 'avalanche';
    };
    url: '/api/v1/wallets/{address}/balance';
};

export type GetNativeBalanceResponses = {
    /**
     * Native balance in wei
     */
    200: SuccessEnvelope & {
        data?: NativeBalance;
    };
};

export type GetNativeBalanceResponse = GetNativeBalanceResponses[keyof GetNativeBalanceResponses];

export type GetTokenBalancesData = {
    body?: never;
    path: {
        address: string;
    };
    query?: {
        /**
         * Moralis chain identifier. Defaults to `eth`.
         */
        chain?: 'eth' | 'polygon' | 'bsc' | 'optimism' | 'arbitrum' | 'base' | 'avalanche';
    };
    url: '/api/v1/wallets/{address}/tokens';
};

export type GetTokenBalancesResponses = {
    /**
     * List of ERC-20 token balances
     */
    200: SuccessEnvelope & {
        data?: Array<Token>;
    };
};

export type GetTokenBalancesResponse = GetTokenBalancesResponses[keyof GetTokenBalancesResponses];

export type GetNftsData = {
    body?: never;
    path: {
        address: string;
    };
    query?: {
        /**
         * Moralis chain identifier. Defaults to `eth`.
         */
        chain?: 'eth' | 'polygon' | 'bsc' | 'optimism' | 'arbitrum' | 'base' | 'avalanche';
    };
    url: '/api/v1/wallets/{address}/nfts';
};

export type GetNftsResponses = {
    /**
     * List of NFTs
     */
    200: SuccessEnvelope & {
        data?: Array<Nft>;
    };
};

export type GetNftsResponse = GetNftsResponses[keyof GetNftsResponses];

export type GetWalletHistoryData = {
    body?: never;
    path: {
        address: string;
    };
    query?: {
        /**
         * Moralis chain identifier. Defaults to `eth`.
         */
        chain?: 'eth' | 'polygon' | 'bsc' | 'optimism' | 'arbitrum' | 'base' | 'avalanche';
    };
    url: '/api/v1/wallets/{address}/history';
};

export type GetWalletHistoryResponses = {
    /**
     * Decoded activity entries
     */
    200: SuccessEnvelope & {
        data?: Array<HistoryEntry>;
    };
};

export type GetWalletHistoryResponse = GetWalletHistoryResponses[keyof GetWalletHistoryResponses];

export type GetTransactionsData = {
    body?: never;
    path: {
        address: string;
    };
    query?: {
        /**
         * Moralis chain identifier. Defaults to `eth`.
         */
        chain?: 'eth' | 'polygon' | 'bsc' | 'optimism' | 'arbitrum' | 'base' | 'avalanche';
    };
    url: '/api/v1/wallets/{address}/transactions';
};

export type GetTransactionsResponses = {
    /**
     * Raw transaction list
     */
    200: SuccessEnvelope & {
        data?: Array<Transaction>;
    };
};

export type GetTransactionsResponse = GetTransactionsResponses[keyof GetTransactionsResponses];

export type GetDeFiPositionsData = {
    body?: never;
    path: {
        address: string;
    };
    query?: {
        /**
         * Moralis chain identifier. Defaults to `eth`.
         */
        chain?: 'eth' | 'polygon' | 'bsc' | 'optimism' | 'arbitrum' | 'base' | 'avalanche';
    };
    url: '/api/v1/wallets/{address}/defi';
};

export type GetDeFiPositionsResponses = {
    /**
     * List of DeFi positions
     */
    200: SuccessEnvelope & {
        data?: Array<DeFiPosition>;
    };
};

export type GetDeFiPositionsResponse = GetDeFiPositionsResponses[keyof GetDeFiPositionsResponses];

export type GetNetWorthData = {
    body?: never;
    path: {
        address: string;
    };
    query?: {
        /**
         * One or more chain identifiers. Defaults to `[eth]`.
         */
        'chains[]'?: Array<string>;
    };
    url: '/api/v1/wallets/{address}/net-worth';
};

export type GetNetWorthResponses = {
    /**
     * Aggregated net worth
     */
    200: SuccessEnvelope & {
        data?: NetWorth;
    };
};

export type GetNetWorthResponse = GetNetWorthResponses[keyof GetNetWorthResponses];

export type GetPnLSummaryData = {
    body?: never;
    path: {
        address: string;
    };
    query?: {
        /**
         * Moralis chain identifier. Defaults to `eth`.
         */
        chain?: 'eth' | 'polygon' | 'bsc' | 'optimism' | 'arbitrum' | 'base' | 'avalanche';
        /**
         * Lookback window in days. 0 means all time.
         */
        days?: number;
    };
    url: '/api/v1/wallets/{address}/pnl';
};

export type GetPnLSummaryResponses = {
    /**
     * P&L summary
     */
    200: SuccessEnvelope & {
        data?: PnLSummary;
    };
};

export type GetPnLSummaryResponse = GetPnLSummaryResponses[keyof GetPnLSummaryResponses];

export type GetPnLBreakdownData = {
    body?: never;
    path: {
        address: string;
    };
    query?: {
        /**
         * Moralis chain identifier. Defaults to `eth`.
         */
        chain?: 'eth' | 'polygon' | 'bsc' | 'optimism' | 'arbitrum' | 'base' | 'avalanche';
        /**
         * Lookback window in days. 0 means all time.
         */
        days?: number;
    };
    url: '/api/v1/wallets/{address}/pnl/breakdown';
};

export type GetPnLBreakdownResponses = {
    /**
     * Per-token P&L list
     */
    200: SuccessEnvelope & {
        data?: Array<TokenPnL>;
    };
};

export type GetPnLBreakdownResponse = GetPnLBreakdownResponses[keyof GetPnLBreakdownResponses];

export type ResolveEnsData = {
    body?: never;
    path: {
        address: string;
    };
    query?: never;
    url: '/api/v1/wallets/{address}/ens';
};

export type ResolveEnsResponses = {
    /**
     * Resolved ENS info
     */
    200: SuccessEnvelope & {
        data?: EnsInfo;
    };
};

export type ResolveEnsResponse = ResolveEnsResponses[keyof ResolveEnsResponses];

export type GetApprovalsData = {
    body?: never;
    path: {
        address: string;
    };
    query?: {
        /**
         * Moralis chain identifier. Defaults to `eth`.
         */
        chain?: 'eth' | 'polygon' | 'bsc' | 'optimism' | 'arbitrum' | 'base' | 'avalanche';
    };
    url: '/api/v1/wallets/{address}/approvals';
};

export type GetApprovalsResponses = {
    /**
     * List of active approvals
     */
    200: SuccessEnvelope & {
        data?: Array<Approval>;
    };
};

export type GetApprovalsResponse = GetApprovalsResponses[keyof GetApprovalsResponses];

export type GetSwapChainsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/swap/chains';
};

export type GetSwapChainsResponses = {
    /**
     * List of EVM chains from LI.FI
     */
    200: SuccessEnvelope & {
        data?: Array<LifiChain>;
    };
};

export type GetSwapChainsResponse = GetSwapChainsResponses[keyof GetSwapChainsResponses];

export type GetSwapTokensData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Numeric EVM chain ID.
         */
        chainId: number;
    };
    url: '/api/v1/swap/tokens';
};

export type GetSwapTokensErrors = {
    /**
     * Missing or invalid chainId
     */
    400: ErrorEnvelope;
};

export type GetSwapTokensError = GetSwapTokensErrors[keyof GetSwapTokensErrors];

export type GetSwapTokensResponses = {
    /**
     * List of tokens on the given chain
     */
    200: SuccessEnvelope & {
        data?: Array<LifiToken>;
    };
};

export type GetSwapTokensResponse = GetSwapTokensResponses[keyof GetSwapTokensResponses];

export type GetSwapQuoteData = {
    body?: never;
    path?: never;
    query: {
        fromChain: number;
        toChain: number;
        /**
         * Token contract address on the source chain.
         */
        fromToken: string;
        /**
         * Token contract address on the destination chain.
         */
        toToken: string;
        /**
         * Amount in smallest unit (wei).
         */
        fromAmount: string;
        /**
         * Sender wallet address.
         */
        fromAddress: string;
        /**
         * Max allowed slippage as a decimal (e.g. 0.005 = 0.5%). Defaults to 0.005.
         */
        slippage?: number;
    };
    url: '/api/v1/swap/quote';
};

export type GetSwapQuoteErrors = {
    /**
     * Missing or invalid parameters
     */
    400: ErrorEnvelope;
    /**
     * LI.FI returned no route or upstream error
     */
    500: ErrorEnvelope;
};

export type GetSwapQuoteError = GetSwapQuoteErrors[keyof GetSwapQuoteErrors];

export type GetSwapQuoteResponses = {
    /**
     * Swap quote with ready-to-sign transaction
     */
    200: SuccessEnvelope & {
        data?: LifiQuote;
    };
};

export type GetSwapQuoteResponse = GetSwapQuoteResponses[keyof GetSwapQuoteResponses];
