// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApprovalsData, GetApprovalsResponses, GetDeFiPositionsData, GetDeFiPositionsResponses, GetNativeBalanceData, GetNativeBalanceResponses, GetNetWorthData, GetNetWorthResponses, GetNftsData, GetNftsResponses, GetPnLBreakdownData, GetPnLBreakdownResponses, GetPnLSummaryData, GetPnLSummaryResponses, GetSwapChainsData, GetSwapChainsResponses, GetSwapQuoteData, GetSwapQuoteErrors, GetSwapQuoteResponses, GetSwapTokensData, GetSwapTokensErrors, GetSwapTokensResponses, GetTokenBalancesData, GetTokenBalancesResponses, GetTransactionsData, GetTransactionsResponses, GetWalletData, GetWalletErrors, GetWalletHistoryData, GetWalletHistoryResponses, GetWalletResponses, HealthCheckData, HealthCheckResponses, ResolveEnsData, ResolveEnsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Get a stored wallet
 */
export const getWallet = <ThrowOnError extends boolean = false>(options: Options<GetWalletData, ThrowOnError>) => (options.client ?? client).get<GetWalletResponses, GetWalletErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/wallets/{address}',
    ...options
});

/**
 * Get native token balance
 */
export const getNativeBalance = <ThrowOnError extends boolean = false>(options: Options<GetNativeBalanceData, ThrowOnError>) => (options.client ?? client).get<GetNativeBalanceResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/wallets/{address}/balance',
    ...options
});

/**
 * Get ERC-20 token balances
 */
export const getTokenBalances = <ThrowOnError extends boolean = false>(options: Options<GetTokenBalancesData, ThrowOnError>) => (options.client ?? client).get<GetTokenBalancesResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/wallets/{address}/tokens',
    ...options
});

/**
 * Get NFT holdings
 */
export const getNfts = <ThrowOnError extends boolean = false>(options: Options<GetNftsData, ThrowOnError>) => (options.client ?? client).get<GetNftsResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/wallets/{address}/nfts',
    ...options
});

/**
 * Get decoded wallet activity history
 */
export const getWalletHistory = <ThrowOnError extends boolean = false>(options: Options<GetWalletHistoryData, ThrowOnError>) => (options.client ?? client).get<GetWalletHistoryResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/wallets/{address}/history',
    ...options
});

/**
 * Get raw on-chain transactions
 */
export const getTransactions = <ThrowOnError extends boolean = false>(options: Options<GetTransactionsData, ThrowOnError>) => (options.client ?? client).get<GetTransactionsResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/wallets/{address}/transactions',
    ...options
});

/**
 * Get DeFi protocol positions
 */
export const getDeFiPositions = <ThrowOnError extends boolean = false>(options: Options<GetDeFiPositionsData, ThrowOnError>) => (options.client ?? client).get<GetDeFiPositionsResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/wallets/{address}/defi',
    ...options
});

/**
 * Get total net worth across chains
 */
export const getNetWorth = <ThrowOnError extends boolean = false>(options: Options<GetNetWorthData, ThrowOnError>) => (options.client ?? client).get<GetNetWorthResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/wallets/{address}/net-worth',
    ...options
});

/**
 * Get P&L summary
 */
export const getPnLSummary = <ThrowOnError extends boolean = false>(options: Options<GetPnLSummaryData, ThrowOnError>) => (options.client ?? client).get<GetPnLSummaryResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/wallets/{address}/pnl',
    ...options
});

/**
 * Get per-token P&L breakdown
 */
export const getPnLBreakdown = <ThrowOnError extends boolean = false>(options: Options<GetPnLBreakdownData, ThrowOnError>) => (options.client ?? client).get<GetPnLBreakdownResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/wallets/{address}/pnl/breakdown',
    ...options
});

/**
 * Resolve ENS name for an address
 */
export const resolveEns = <ThrowOnError extends boolean = false>(options: Options<ResolveEnsData, ThrowOnError>) => (options.client ?? client).get<ResolveEnsResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/wallets/{address}/ens',
    ...options
});

/**
 * Get active ERC-20 token approvals
 */
export const getApprovals = <ThrowOnError extends boolean = false>(options: Options<GetApprovalsData, ThrowOnError>) => (options.client ?? client).get<GetApprovalsResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/wallets/{address}/approvals',
    ...options
});

/**
 * List supported EVM chains for swapping
 */
export const getSwapChains = <ThrowOnError extends boolean = false>(options?: Options<GetSwapChainsData, ThrowOnError>) => (options?.client ?? client).get<GetSwapChainsResponses, unknown, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/swap/chains',
    ...options
});

/**
 * List tokens available for swapping on a chain
 */
export const getSwapTokens = <ThrowOnError extends boolean = false>(options: Options<GetSwapTokensData, ThrowOnError>) => (options.client ?? client).get<GetSwapTokensResponses, GetSwapTokensErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/swap/tokens',
    ...options
});

/**
 * Get a swap/bridge quote
 */
export const getSwapQuote = <ThrowOnError extends boolean = false>(options: Options<GetSwapQuoteData, ThrowOnError>) => (options.client ?? client).get<GetSwapQuoteResponses, GetSwapQuoteErrors, ThrowOnError>({
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/api/v1/swap/quote',
    ...options
});
